define("confluence/menu",["ajs","jquery","document","window","confluence/api/ajax"],function(d,c,g,i,p){var h={};d.menuShowCount=0;var j=function(a){c(a).closest(".ajs-menu-bar").find(".ajs-drop-down").each(function(){this.hide()})},l=function(a){return c(a).closest(".ajs-menu-bar").hasClass("menu-bar-open")},m=function(a){c(a).closest(".ajs-menu-bar").addClass("menu-bar-open")},n=function(a){c(a).closest(".ajs-menu-bar").removeClass("menu-bar-open")};h.ajsMenu=function(a){a=a||{};c(".ajs-button",
this).each(function(){c(this).mouseover(function(){var a=this,d=l(a);j(a);if(d){var b=c(g),e=function(){n(a);return!1};b.unbind("click.menu");setTimeout(function(){b.one("click.menu",e)},1);m(a)}})});c(".ajs-menu-item",this).each(function(){c(this).ajsMenuItem(a)})};h.ajsMenuItem=function(a){var a=a||{},d=this,f=c(this),b=c(".ajs-drop-down",d);if(b.length){b=b[0];b.hidden=!0;b.focused=-1;b.hide=function(){if(!this.hidden){f.toggleClass("opened");0===c(d.parentNode).find(".opened").length&&n(d);var b=
c("a",this);c(this).toggleClass("assistive");this.hidden=!0;c(g).unbind("click",this.fhide).unbind("keydown",this.fmovefocus).unbind("keypress",this.blocker);this.focused+1&&c(b[this.focused]).removeClass("active");this.focused=-1}};b.show=function(){if("undefined"===typeof this.hidden||this.hidden){var b=this,e=c(this);e.toggleClass("assistive");f.toggleClass("opened");m(d);this.hidden=!1;this.timer=setTimeout(function(){c(g).click(b.fhide)},1);c(g).keydown(b.fmovefocus).keypress(b.blocker);var k=
c("a",b);k.each(function(b){var a=this.parentNode.parentNode;c(this).hover(function(){a.focused+1&&c(k[a.focused].parentNode).removeClass("active");c(this.parentNode).addClass("active");a.focused=b},function(){a.focused+1&&c(k[a.focused].parentNode).removeClass("active");a.focused=-1})});var o=i.pageYOffset||g.documentElement.scrollTop,q=o+c(i).height();e.removeClass("above");!a.isFixedPosition&&e.offset().top+e.height()>q&&(e.addClass("above"),e.offset().top<o&&e.removeClass("above"))}};b.isMenuBarOpened=
function(){return l(b)};b.closeOthers=function(){j(b)};b.fmovefocus=function(a){b.movefocus(a)};b.fhide=function(a){b.hide(a);return 0<c(a.target).closest(".ajs-drop-down").length};b.blocker=function(a){a=a.which;if(40===a||38===a)return!1};b.movefocus=function(a){var b=a.which,d=this.getElementsByTagName("a"),e=this.focused,f=9===b,g;do{switch(b){case 40:case 9:a.shiftKey?this.focused--:this.focused++;break;case 38:this.focused--;break;case 27:return this.hide(),!1;default:return!0}g=0>this.focused||
this.focused>d.length-1}while(!g&&c(d[this.focused].parentNode).hasClass("assistive"));if(f&&g)return-1!=e&&c(d[e].parentNode).removeClass("active"),this.focused=-1,this.hide(),!1;f||(0>this.focused?this.focused=d.length-1:this.focused>d.length-1&&(this.focused=0));0<=e&&c(d[e].parentNode).removeClass("active");d[this.focused].focus();c(d[this.focused].parentNode).addClass("active");a.stopPropagation();a.preventDefault();return!1};var e=c(".trigger",d);e.length&&(f.mouseover(function(){b.isMenuBarOpened()?
b.hidden&&(j(b),b.show()):f.addClass("hover")}),f.mouseout(function(){b.isMenuBarOpened()||f.removeClass("hover")}),e.click(function(){if(b.hidden){e.parent("li").removeClass("hover");var a=0<c(".ajs-menu-bar.menu-bar-open").length;b.show();return a}b.hide();e.parent("li").addClass("hover");return!1}))}};h.initialiser=function(a){a("#view-user-history-link").click(function(a){i.open(this.href,(this.id+"-popupwindow").replace(/-/g,"_"),"width=600, height=400, scrollbars, resizable");a.preventDefault();
return!1});var c=function(b){-1===a("#action-messages").html().indexOf(b)&&d.messages.error("#action-messages",{body:b})};a("#page-favourite").click(function(b){var e=a(this),f=e.find(".aui-icon");if(e.hasClass("waiting"))return d.stopEvent(b);e.addClass("waiting");var g=d.contextPath()+"/rest/experimental/relation/user/current/favourite/toContent/"+d.params.pageId,h=e.hasClass("selected")?"DELETE":"PUT";p.ajax({url:g,type:h,contentType:"application/json",data:{},success:function(){var a=e.hasClass("selected");
e.toggleClass("selected ie-page-favourite-selected",!a);var b=!a?d.I18n.getText("pagemenu.unfavourite.tooltip"):d.I18n.getText("pagemenu.favourite.tooltip"),b=b+(" ("+d.I18n.getText("pagemenu.favourite.accesskey")+")"),c=!a?d.I18n.getText("pagemenu.unfavourite","<u>","</u>"):d.I18n.getText("pagemenu.favourite","<u>","</u>");e.children("span").empty().append(f).append(" ").append(c);e.attr("title",b);f.toggleClass("aui-iconfont-unstar",a);f.toggleClass("aui-iconfont-star",!a);e.removeClass("waiting");
e.blur();d.trigger("analytics",{name:"confluence.page.page-menu."+(a?"favourite":"unfavourite")})},error:function(a){403===a.status?c("You are not permitted to perform this operation."):c("Server error while updating favourite");e.removeClass("waiting");e.blur()}});return d.stopEvent(b)});var f=a("#action-menu-link");f.length&&f.next().addClass("most-right-menu-item");a("#action-menu").on({"aui-dropdown2-show":function(){a(this).css({right:function(){return a(i).width()-f.offset().left-f.outerWidth(!0)-
1},left:"auto"})}});a(".ajs-menu-bar").ajsMenu({isFixedPosition:!0})};h.ieHack=function(){c("#header-menu-bar .ajs-menu-item").each(function(){var a=c(this),g=c(".ajs-drop-down",this),a=a.width();a>g.width()&&(g.width(a.valueOf()+50),d.log("Dropdown width override occurred"))});c("#user-menu-link-content .user-item").on("click",function(){d.trigger("analyticsEvent",{name:"user-menu-item.clicked",data:{id:c(this).attr("id")}})});c("#user-menu-link-content").on({"aui-dropdown2-show":function(){d.trigger("analyticsEvent",
{name:"confluence.user-menu.show"})},"aui-dropdown2-hide":function(){d.trigger("analyticsEvent",{name:"confluence.user-menu.hide"})}})};return h});require("confluence/module-exporter").safeRequire("confluence/menu",function(d){var c=require("jquery"),g=require("ajs");c.fn.ajsMenu=d.ajsMenu;c.fn.ajsMenuItem=d.ajsMenuItem;g.toInit(d.initialiser);g.toInit(d.ieHack)});